package Model;
import java.sql.*;

public class Patient {

    private int patientId, mrn;
    private String firstName, lastName, address, city, state, zipcode, homePhone, cellPhone, emailAddress;
    private Connection connection;

    // get existing patient
    public Patient(Connection connection, int patientId) {
        this.connection = connection;
        this.patientId = patientId;
        this.get();
    }

    // create new patient [ no patient id for new patient < generated by database > ]
    public Patient(Connection connection, int mrn, String firstName,
                   String lastName, String address, String city, String state, String zipcode,
                   String homePhone, String cellPhone, String emailAddress) {
        // call 'update' constructor -- pass -1 as patientId
        this(connection, -1, mrn, firstName,
                lastName, address, city, state, zipcode,
                homePhone, cellPhone, emailAddress);
    }

    // update existing patient [ no patient id for new patient < generated by database > ]
    public Patient(Connection connection, int patientId, int mrn, String firstName,
                   String lastName, String address, String city, String state, String zipcode,
                   String homePhone, String cellPhone, String emailAddress) {
        super();
        this.connection = connection;
        this.patientId = patientId;
        this.mrn = mrn;
        this.zipcode = zipcode;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.city = city;
        this.state = state;
        this.homePhone = homePhone;
        this.cellPhone = cellPhone;
        this.emailAddress = emailAddress;
        if(patientId == -1) {
            this.create();
        } else {
            this.update();
        }
    }

    public int getPatientId() {
        return patientId;
    }

    // don't allow outside access to patientId
    private void setPatientId(int patientId) {
        this.patientId = patientId;
    }

    public int getMrn() {
        return mrn;
    }

    public void setMrn(int mrn) {
        this.mrn = mrn;
    }

    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getHomePhone() {
        return homePhone;
    }

    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    public String getCellPhone() {
        return cellPhone;
    }

    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    private void get() {
        PreparedStatement statement = null;
        try {
            String query = "select * from AppointmentBook.dbo.patients where patientId = ?";
            statement = connection.prepareStatement(query);
            statement.setInt(1, patientId);
            ResultSet resultSet = statement.executeQuery();
            resultSet.next();

            // map database values to object
            setMrn(resultSet.getInt("MRN"));
            setFirstName(resultSet.getString("firstName"));
            setLastName(resultSet.getString("lastName"));
            setAddress(resultSet.getString("streetAddress"));
            setCity(resultSet.getString("city"));
            setState(resultSet.getString("state"));
            setZipcode(resultSet.getString("zipcode"));
            setHomePhone(resultSet.getString("homePhone"));
            setCellPhone(resultSet.getString("cellPhone"));
            setEmailAddress(resultSet.getString("emailAddress"));

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void create() {
        PreparedStatement statement = null;
        try {
            String query = "INSERT INTO [dbo].[patients]" +
            "([MRN],[firstName],[lastName],[streetAddress],[city],[state],[zipcode],[homePhone],[cellPhone],[emailAddress])" +
            "VALUES(?,?,?,?,?,?,?,?,?,?)";
            statement = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            statement.setInt(1, getMrn());
            statement.setString(2, getFirstName());
            statement.setString(3, getLastName());
            statement.setString(4, getAddress());
            statement.setString(5, getCity());
            statement.setString(6, getState());
            statement.setString(7, getZipcode());
            statement.setString(8, getHomePhone());
            statement.setString(9, getCellPhone());
            statement.setString(10, getEmailAddress());
            statement.execute();

            // get identity value
            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()) {
                patientId = generatedKeys.getInt(1);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void update() {

    }
    private void delete() {

    }
}